<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="group10-PC" name="com.arc.testcases.Manage.EditProjectDetailsTest" tests="1" failures="0" timestamp="31 Jan 2017 07:29:33 GMT" time="0.000" errors="1">
  <testcase name="editProjectDetailsTest" time="0.000" classname="com.arc.testcases.Manage.EditProjectDetailsTest">
    <error type="java.lang.Throwable" message="Method EditProjectDetailsTest.editProjectDetailsTest()[pri:0, instance:com.arc.testcases.Manage.EditProjectDetailsTest@7e0b0338] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method EditProjectDetailsTest.editProjectDetailsTest()[pri:0, instance:com.arc.testcases.Manage.EditProjectDetailsTest@7e0b0338] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- editProjectDetailsTest -->
</testsuite> <!-- com.arc.testcases.Manage.EditProjectDetailsTest -->
